#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at https://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: release
      r_github_packages:
        - jimhester/covr
      r_check_args: --no-codoc --no-examples --no-tests --ignore-vignettes
      after_success:
        - travis_wait Rscript --version
        - travis_wait Rscript -e 1+1
        - travis_wait Rscript -e '1+2'
        - travis_wait Rscript -e "'2+3'"
        - travis_wait Rscript -e "'covr::codecov(quiet = FALSE)'"
        - travis_wait Rscript -e 'covr::codecov(quiet = FALSE)'
      env:
        - NB='w/ covr' ## Just a label

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'

notifications:
  email:
    on_success: change
    on_failure: change
